/* ─────────────────────────────────────────
   export.js — 產生 DESIGN.md 內容
   ───────────────────────────────────────── */

const SHADOW_TOKENS = {
  none: {
    label: 'None',
    sm: 'none',
    md: 'none',
    lg: 'none'
  },
  soft: {
    label: 'Subtle',
    sm: '0 1px 2px rgba(0, 0, 0, 0.05)',
    md: '0 4px 6px rgba(0, 0, 0, 0.07), 0 2px 4px rgba(0, 0, 0, 0.05)',
    lg: '0 10px 15px rgba(0, 0, 0, 0.08), 0 4px 6px rgba(0, 0, 0, 0.05)'
  },
  medium: {
    label: 'Medium',
    sm: '0 1px 3px rgba(0, 0, 0, 0.10), 0 1px 2px rgba(0, 0, 0, 0.06)',
    md: '0 4px 12px rgba(0, 0, 0, 0.12), 0 2px 4px rgba(0, 0, 0, 0.08)',
    lg: '0 10px 25px rgba(0, 0, 0, 0.15), 0 6px 10px rgba(0, 0, 0, 0.10)'
  },
  strong: {
    label: 'Strong',
    sm: '0 2px 6px rgba(0, 0, 0, 0.15)',
    md: '0 8px 20px rgba(0, 0, 0, 0.18), 0 4px 8px rgba(0, 0, 0, 0.12)',
    lg: '0 20px 40px rgba(0, 0, 0, 0.22), 0 8px 16px rgba(0, 0, 0, 0.15)'
  }
};

const SIZE_USAGE = {
  xs:   'Labels, helper text',
  sm:   'Secondary text, captions',
  base: 'Body copy',
  lg:   'Subheadings, emphasized text',
  xl:   'Section headings',
  '2xl': 'Page titles',
  '3xl': 'Hero headings, key visuals'
};

const LINE_HEIGHT_VALUES = {
  compact:  { body: 1.5,  heading: 1.1 },
  normal:   { body: 1.6,  heading: 1.2 },
  relaxed:  { body: 1.75, heading: 1.3 }
};

const LINE_HEIGHT_LABELS = {
  compact: 'Compact',
  normal:  'Normal',
  relaxed: 'Relaxed'
};

/** Generate full DESIGN.md string from state */
function generateDesignMd(state) {
  const date = new Date().toISOString().slice(0, 10);
  const lines = [];
  const add = (...args) => lines.push(...args);

  // ── Header ──
  add(
    `# DESIGN.md`,
    ``,
    `> Auto-generated by **Design MD Generator** · ${date}`,
    `> To customize, edit this file directly or regenerate via the tool.`,
    ``
  );

  add(`---`, ``);

  // ── Section 1 ──
  add(`## 1. Visual Theme & Mood`, ``);

  const styleList = state.styles.length > 0
    ? state.styles.join(', ')
    : '(not set)';
  add(`**Style:** ${styleList}`, ``);

  if (state.brandPersonality) {
    add(`**Brand Personality:** ${state.brandPersonality}`, ``);
  }
  add(``);

  add(`---`, ``);

  // ── Section 2 ──
  add(`## 2. Color System`, ``);

  // 2a. Primitive brand colors
  add(`### Brand Colors (Primitive Tokens)`, ``);
  add(`| Role | Hex | Usage |`);
  add(`| :--- | :--- | :--- |`);
  add(`| Primary    | \`${state.colorPrimary.toUpperCase()}\`   | CTA buttons, links, interactive highlights |`);
  add(`| Secondary  | \`${state.colorSecondary.toUpperCase()}\` | Secondary actions, informational hints |`);
  add(`| Accent     | \`${state.colorAccent.toUpperCase()}\`   | Tags, alerts, special emphasis |`);
  add(`| Background | \`${state.colorBg.toUpperCase()}\`       | Page background, container fill |`);
  add(`| Text       | \`${state.colorText.toUpperCase()}\`     | Primary text, headings |`);
  add(``);

  // 2b. Generated color scales
  const pvars = generateVariants(state.colorPrimary);
  const svars = generateVariants(state.colorSecondary);
  const avars = generateVariants(state.colorAccent);

  add(`### Generated Color Scales`, ``);
  add(`**Primary Variants**`);
  add(`| State | Hex |`);
  add(`| :--- | :--- |`);
  add(`| Hover | \`${pvars.hover.toUpperCase()}\` |`);
  add(`| Light | \`${pvars.light.toUpperCase()}\` |`);
  add(`| Dark  | \`${pvars.dark.toUpperCase()}\`  |`);
  add(``);
  add(`**Secondary Variants**`);
  add(`| State | Hex |`);
  add(`| :--- | :--- |`);
  add(`| Hover | \`${svars.hover.toUpperCase()}\` |`);
  add(`| Light | \`${svars.light.toUpperCase()}\` |`);
  add(`| Dark  | \`${svars.dark.toUpperCase()}\`  |`);
  add(``);
  add(`**Accent Variants**`);
  add(`| State | Hex |`);
  add(`| :--- | :--- |`);
  add(`| Hover | \`${avars.hover.toUpperCase()}\` |`);
  add(`| Light | \`${avars.light.toUpperCase()}\` |`);
  add(`| Dark  | \`${avars.dark.toUpperCase()}\`  |`);
  add(``);

  // 2c. Semantic token mapping
  add(`### Semantic Token Mapping`, ``);
  add(`| Token | Maps to | Description |`);
  add(`| :--- | :--- | :--- |`);
  add(`| \`--color-action\`       | Primary       | Buttons, links, interactive elements |`);
  add(`| \`--color-action-hover\` | Primary Hover | Hover state of interactive elements |`);
  add(`| \`--color-info\`         | Secondary     | Informational cues, secondary actions |`);
  add(`| \`--color-highlight\`    | Accent        | Tags, alerts, special emphasis |`);
  add(`| \`--color-surface\`      | Background    | Containers, card backgrounds |`);
  add(`| \`--color-on-surface\`   | Text          | Primary text |`);
  add(`| \`--color-muted\`        | Text 50%      | Secondary text, descriptions |`);
  add(``);

  // 2d. CSS variables
  add(`\`\`\`css`);
  add(`/* Primitive Color Tokens */`);
  add(`--color-primary:    ${state.colorPrimary.toUpperCase()};`);
  add(`--color-secondary:  ${state.colorSecondary.toUpperCase()};`);
  add(`--color-accent:     ${state.colorAccent.toUpperCase()};`);
  add(`--color-bg:         ${state.colorBg.toUpperCase()};`);
  add(`--color-text:       ${state.colorText.toUpperCase()};`);
  add(``);
  add(`/* Semantic Tokens */`);
  add(`--color-action:        var(--color-primary);`);
  add(`--color-action-hover:  ${pvars.hover.toUpperCase()};`);
  add(`--color-info:          var(--color-secondary);`);
  add(`--color-highlight:     var(--color-accent);`);
  add(`--color-surface:       var(--color-bg);`);
  add(`--color-on-surface:    var(--color-text);`);
  add(`\`\`\``);
  add(``);

  // 2e. WCAG contrast
  const ratioPB = getContrastRatio(state.colorPrimary, state.colorBg);
  const ratioSB = getContrastRatio(state.colorSecondary, state.colorBg);
  const ratioTB = getContrastRatio(state.colorText, state.colorBg);

  add(`### WCAG 2.1 Contrast Ratios`, ``);
  add(`| Pair | Ratio | AA (4.5:1) | AAA (7:1) |`);
  add(`| :--- | ---: | :---: | :---: |`);
  add(`| Primary / Background   | ${ratioPB.toFixed(2)}:1 | ${ratioPB >= 4.5 ? '✅' : '❌'} | ${ratioPB >= 7 ? '✅' : '❌'} |`);
  add(`| Secondary / Background | ${ratioSB.toFixed(2)}:1 | ${ratioSB >= 4.5 ? '✅' : '❌'} | ${ratioSB >= 7 ? '✅' : '❌'} |`);
  add(`| Text / Background      | ${ratioTB.toFixed(2)}:1 | ${ratioTB >= 4.5 ? '✅' : '❌'} | ${ratioTB >= 7 ? '✅' : '❌'} |`);
  add(``);

  // 2f. Color usage principles
  add(`### Color Usage Principles`, ``);
  add(`- **Consistent state colors**: Hover, Active, and Focus states must always extend from the Primary scale — never mix in other color families`);
  add(`- **Semantic tokens first**: Use \`--color-action\`, \`--color-info\`, etc. in components — never reference raw Hex values directly`);
  add(`- **Background contrast**: Text-to-background contrast must meet WCAG AA (4.5:1) or higher`);
  add(``);

  add(`---`, ``);

  // ── Section 3 ──
  add(`## 3. Typography`, ``);
  add(`| Type | Font |`);
  add(`| :--- | :--- |`);
  add(`| CJK Font   | ${state.fontZh} |`);
  add(`| Latin Font | ${state.fontEn} |`);
  add(``);

  // Line height
  const lhKey = (state.lineHeight && LINE_HEIGHT_VALUES[state.lineHeight]) ? state.lineHeight : 'normal';
  const lh = LINE_HEIGHT_VALUES[lhKey];
  add(`### Line Height (${LINE_HEIGHT_LABELS[lhKey]})`, ``);
  add(`| Type | Value |`);
  add(`| :--- | :--- |`);
  add(`| Body    | ${lh.body} |`);
  add(`| Heading | ${lh.heading} |`);
  add(``);

  add(`### Type Scale`, ``);
  add(`| Token | px | rem | Usage |`);
  add(`| :--- | ---: | ---: | :--- |`);
  const tokens = ['xs', 'sm', 'base', 'lg', 'xl', '2xl', '3xl'];
  for (const token of tokens) {
    const px = state.sizes[token] || 16;
    const rem = (px / 16).toFixed(3).replace(/\.?0+$/, '');
    add(`| \`${token}\` | ${px}px | ${rem}rem | ${SIZE_USAGE[token]} |`);
  }
  add(``);

  // CSS variables
  add(`\`\`\`css`);
  add(`/* Typography CSS Variables */`);
  add(`--font-zh:   '${state.fontZh}', serif;`);
  add(`--font-en:   '${state.fontEn}', sans-serif;`);
  add(``);
  add(`/* Line Height */`);
  add(`--leading-body:    ${lh.body};`);
  add(`--leading-heading: ${lh.heading};`);
  add(``);
  for (const token of tokens) {
    add(`--text-${token}: ${state.sizes[token]}px;`);
  }
  add(`\`\`\``);
  add(``);

  add(`---`, ``);

  // ── Section 4 ──
  add(`## 4. Component Styles`, ``);
  add(`| Setting | Value |`);
  add(`| :--- | :--- |`);
  add(`| Button Radius | ${{ sharp: 'Sharp (3px)', medium: 'Medium (10px)', rounded: 'Rounded (20px)' }[({ 3:'sharp',10:'medium',20:'rounded' })[state.btnRadius]] || `${state.btnRadius}px`} |`);
  add(`| Input Style | ${state.inputStyle === 'bordered' ? 'Bordered' : 'Underline'} |`);
  add(`| Card Style | ${state.cardStyle === 'bordered' ? 'Subtle Border (flat, thin outline)' : 'Elevated Shadow (raised card)'} |`);
  add(``);
  add(`\`\`\`css`);
  add(`/* Component CSS Variables */`);
  add(`--radius-btn:   ${state.btnRadius}px;`);
  add(`--input-style:  ${state.inputStyle};`);
  add(`--card-style:   ${state.cardStyle};`);
  add(`\`\`\``);
  add(``);

  add(`---`, ``);

  // ── Section 5 ──
  add(`## 5. Layout`, ``);
  add(`| Setting | Value |`);
  add(`| :--- | :--- |`);
  add(`| Base Spacing Unit | ${state.spacingBase}px |`);
  add(`| Max Content Width | ${state.maxWidth}px |`);
  add(`| Grid Columns | ${state.gridCols} |`);
  add(``);

  // Breakpoints
  add(`### Breakpoints`, ``);
  add(`| Token | Width | Device |`);
  add(`| :--- | ---: | :--- |`);
  add(`| \`sm\`  |  640px | Large phone (landscape) |`);
  add(`| \`md\`  |  768px | Tablet |`);
  add(`| \`lg\`  | 1024px | Small laptop |`);
  add(`| \`xl\`  | 1280px | Desktop |`);
  add(`| \`2xl\` | 1536px | Large screen |`);
  add(``);
  add(`> Content is capped at **${state.maxWidth}px** wide and centered beyond that.`);
  add(`> Default grid is **${state.gridCols} columns**; collapses to single column below \`md\` or as defined per component.`);
  add(``);
  add(`\`\`\`css`);
  add(`/* Breakpoints (use with CSS Media Queries) */`);
  add(`--breakpoint-sm:  640px;`);
  add(`--breakpoint-md:  768px;`);
  add(`--breakpoint-lg:  1024px;`);
  add(`--breakpoint-xl:  1280px;`);
  add(`--breakpoint-2xl: 1536px;`);
  add(`--max-width:      ${state.maxWidth}px;`);
  add(`--grid-cols:      ${state.gridCols};`);
  add(`\`\`\``);
  add(``);

  // Spacing scale
  add(`### Spacing Scale (base: ${state.spacingBase}px)`, ``);
  const base = parseInt(state.spacingBase);
  const spacingTokens = [
    { name: 'xs',  mult: base === 4 ? 1 : 0.5 },
    { name: 'sm',  mult: 1 },
    { name: 'md',  mult: 2 },
    { name: 'lg',  mult: 3 },
    { name: 'xl',  mult: 4 },
    { name: '2xl', mult: 6 },
    { name: '3xl', mult: 8 }
  ];
  add(`| Token | px |`);
  add(`| :--- | ---: |`);
  for (const t of spacingTokens) {
    add(`| \`space-${t.name}\` | ${Math.round(base * t.mult)}px |`);
  }
  add(``);
  add(`\`\`\`css`);
  add(`/* Spacing CSS Variables */`);
  for (const t of spacingTokens) {
    add(`--space-${t.name}: ${Math.round(base * t.mult)}px;`);
  }
  add(`\`\`\``);
  add(``);

  add(`---`, ``);

  // ── Section 6 ──
  add(`## 6. Elevation & Shadow`, ``);
  const st = SHADOW_TOKENS[state.shadowStyle] || SHADOW_TOKENS.soft;
  add(`**Shadow Style:** ${st.label}`, ``);

  add(`### Shadow Layers & Usage`, ``);
  add(`| Layer | Token | Usage |`);
  add(`| :--- | :--- | :--- |`);
  add(`| sm | \`--shadow-sm\` | Cards, inputs, subtle depth |`);
  add(`| md | \`--shadow-md\` | Dropdowns, floating panels, Popovers |`);
  add(`| lg | \`--shadow-lg\` | Modals, Drawers, full-page overlays |`);
  add(``);

  add(`\`\`\`css`);
  add(`/* Shadow CSS Variables */`);
  add(`--shadow-sm: ${st.sm};`);
  add(`--shadow-md: ${st.md};`);
  add(`--shadow-lg: ${st.lg};`);
  add(`\`\`\``);
  add(``);

  add(`---`, ``);

  // ── Section 7 ──
  add(`## 7. z-index Architecture`, ``);
  add(`| Layer | Token | Value | Description |`);
  add(`| :--- | :--- | ---: | :--- |`);
  add(`| Base     | \`--z-base\`     |   0 | Default stacking (no elevation) |`);
  add(`| Sticky   | \`--z-sticky\`   | 100 | Sticky headers, sidebars |`);
  add(`| Dropdown | \`--z-dropdown\` | 200 | Dropdowns, Tooltips |`);
  add(`| Backdrop | \`--z-backdrop\` | 300 | Overlay backdrop |`);
  add(`| Modal    | \`--z-modal\`    | 400 | Modals, Dialogs |`);
  add(`| Toast    | \`--z-toast\`    | 500 | Notifications, Toast messages |`);
  add(``);
  add(`\`\`\`css`);
  add(`/* z-index Layer CSS Variables */`);
  add(`--z-base:      0;`);
  add(`--z-sticky:    100;`);
  add(`--z-dropdown:  200;`);
  add(`--z-backdrop:  300;`);
  add(`--z-modal:     400;`);
  add(`--z-toast:     500;`);
  add(`\`\`\``);
  add(``);

  add(`---`, ``);

  // ── Section 8 ──
  add(`## 8. Guidelines — Do's and Don'ts`, ``);

  const doList  = state.dos.filter(s => s.trim());
  const dontList = state.donts.filter(s => s.trim());

  add(`### ✅ Do's`, ``);
  if (doList.length > 0) {
    for (const d of doList) add(`- ${d}`);
  } else {
    add(`- (not filled in)`);
  }
  add(``);

  add(`### ❌ Don'ts`, ``);
  if (dontList.length > 0) {
    for (const d of dontList) add(`- ${d}`);
  } else {
    add(`- (not filled in)`);
  }
  add(``);

  add(`---`, ``);

  // ── Footer ──
  add(`> ⚡ Generated by [Design MD Generator](https://github.com/) · ${date}`);

  return lines.join('\n');
}
